In [ ]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.simplefilter("ignore")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
path='/content/drive/MyDrive/Colab Notebooks/LanguageDetection(Kaggle).csv'
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/LanguageDetection(Kaggle).csv')

In [ ]:
data.head(10)

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English
5  [2] In ancient philosophy, natura is mostly us...  English
6  [3][4] \nThe concept of nature as a whole, the...  English
7  During the advent of modern scientific method ...  English
8  [5][6] With the Industrial revolution, nature ...  English
9  However, a vitalist vision of nature, closer t...  English

In [ ]:
data["Language"].value_counts()

Language
English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: count, dtype: int64

In [ ]:
X = data["Text"]
y = data["Language"]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
# creating a list for appending the preprocessed text
data_list = []
# iterating through all the text
for text in X:
       # removing the symbols and numbers
        text = re.sub(r'[!@#$(),n"%^*?:;~`0-9]', ' ', text)
        text = re.sub(r'[[]]', ' ', text)
        # converting the text to lower case
        text = text.lower()
        # appending to data_list
        data_list.append(text)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(data_list).toarray()
X.shape # (10337, 39419)

(10337, 34937)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
ac = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy is :",ac)

Accuracy is : 0.9753384912959381


In [ ]:
print("Confusion Matrix: \n", cm)

Confusion Matrix: 
 [[103   0   0   4   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  84   0   2   2   0   0   0   1   0   0   1   0   0   4   0   0]
 [  0   0 105   1   0   1   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 281   0   1   0   0   1   0   0   0   0   0   0   0   0]
 [  0   0   0   2 200   0   0   0   1   0   0   0   0   0   0   0   0]
 [  0   0   0   1   1 100   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  69   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0  19   0   0   0   0   0   0   0   0   0]
 [  0   0   0   1   1   0   0   0 128   0   0   0   0   2   0   0   0]
 [  0   1   0   1   0   0   0   0   0  68   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0  98   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   2   0   0 143   0   0   0   0   0]
 [  0   0   0   5   0   0   0   0   0   0   0   0 146   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0   0   0   0 157

In [ ]:
def predict(text):
     x = cv.transform([text]).toarray() # converting text to bag of words model (Vector)
     lang = model.predict(x) # predicting the language
     lang = le.inverse_transform(lang) # finding the language corresponding the the predicted value
     print("The langauge is in",lang[0]) # printing the language

In [ ]:
predict('مرحبا بكم في قناة utube')

The langauge is in Arabic


In [ ]:
predict('യൂട്യൂബ് കാനലിലേക്ക് സ്വാഗതം')

The langauge is in Malayalam


In [ ]:
predict('ஹாய் வணக்கம்')

The langauge is in Tamil


In [ ]:
predict('भारतीय में आपका स्वागत है')

The langauge is in Hindi
